// Code generated by MockGen. DO NOT EDIT.
// Source: Repository.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	reflect "reflect"

	model "github.com/Baraulia/COURIER_SERVICE/model"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderRep is a mock of OrderRep interface.
type MockOrderRep struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepMockRecorder
}

// MockOrderRepMockRecorder is the mock recorder for MockOrderRep.
type MockOrderRepMockRecorder struct {
	mock *MockOrderRep
}

// NewMockOrderRep creates a new mock instance.
func NewMockOrderRep(ctrl *gomock.Controller) *MockOrderRep {
	mock := &MockOrderRep{ctrl: ctrl}
	mock.recorder = &MockOrderRepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRep) EXPECT() *MockOrderRepMockRecorder {
	return m.recorder
}

// ChangeOrderStatusInDB mocks base method.
func (m *MockOrderRep) ChangeOrderStatusInDB(status string, id uint16) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeOrderStatusInDB", status, id)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeOrderStatusInDB indicates an expected call of ChangeOrderStatusInDB.
func (mr *MockOrderRepMockRecorder) ChangeOrderStatusInDB(status, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeOrderStatusInDB", reflect.TypeOf((*MockOrderRep)(nil).ChangeOrderStatusInDB), status, id)
}

// GetActiveOrderFromDB mocks base method.
func (m *MockOrderRep) GetActiveOrderFromDB(id int) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrderFromDB", id)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrderFromDB indicates an expected call of GetActiveOrderFromDB.
func (mr *MockOrderRepMockRecorder) GetActiveOrderFromDB(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrderFromDB", reflect.TypeOf((*MockOrderRep)(nil).GetActiveOrderFromDB), id)
}

// GetActiveOrdersFromDB mocks base method.
func (m *MockOrderRep) GetActiveOrdersFromDB(id int) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrdersFromDB", id)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrdersFromDB indicates an expected call of GetActiveOrdersFromDB.
func (mr *MockOrderRepMockRecorder) GetActiveOrdersFromDB(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrdersFromDB", reflect.TypeOf((*MockOrderRep)(nil).GetActiveOrdersFromDB), id)
}

// GetAllOrdersOfCourierServiceWithPageFromDB mocks base method.
func (m *MockOrderRep) GetAllOrdersOfCourierServiceWithPageFromDB(limit, page, idService int) ([]model.Order, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrdersOfCourierServiceWithPageFromDB", limit, page, idService)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetAllOrdersOfCourierServiceWithPageFromDB indicates an expected call of GetAllOrdersOfCourierServiceWithPageFromDB.
func (mr *MockOrderRepMockRecorder) GetAllOrdersOfCourierServiceWithPageFromDB(limit, page, idService interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrdersOfCourierServiceWithPageFromDB", reflect.TypeOf((*MockOrderRep)(nil).GetAllOrdersOfCourierServiceWithPageFromDB), limit, page, idService)
}

// GetCourierCompletedOrdersByMouthWithPageFromDB mocks base method.
func (m *MockOrderRep) GetCourierCompletedOrdersByMouthWithPageFromDB(limit, page, idCourier, Month, Year int) ([]model.Order, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierCompletedOrdersByMouthWithPageFromDB", limit, page, idCourier, Month, Year)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetCourierCompletedOrdersByMouthWithPageFromDB indicates an expected call of GetCourierCompletedOrdersByMouthWithPageFromDB.
func (mr *MockOrderRepMockRecorder) GetCourierCompletedOrdersByMouthWithPageFromDB(limit, page, idCourier, Month, Year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierCompletedOrdersByMouthWithPageFromDB", reflect.TypeOf((*MockOrderRep)(nil).GetCourierCompletedOrdersByMouthWithPageFromDB), limit, page, idCourier, Month, Year)
}

// GetCourierCompletedOrdersWithPageFromDB mocks base method.
func (m *MockOrderRep) GetCourierCompletedOrdersWithPageFromDB(limit, page, idCourier int) ([]model.DetailedOrder, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierCompletedOrdersWithPageFromDB", limit, page, idCourier)
	ret0, _ := ret[0].([]model.DetailedOrder)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetCourierCompletedOrdersWithPageFromDB indicates an expected call of GetCourierCompletedOrdersWithPageFromDB.
func (mr *MockOrderRepMockRecorder) GetCourierCompletedOrdersWithPageFromDB(limit, page, idCourier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierCompletedOrdersWithPageFromDB", reflect.TypeOf((*MockOrderRep)(nil).GetCourierCompletedOrdersWithPageFromDB), limit, page, idCourier)
}

// MockCourierRep is a mock of CourierRep interface.
type MockCourierRep struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepMockRecorder
}

// MockCourierRepMockRecorder is the mock recorder for MockCourierRep.
type MockCourierRepMockRecorder struct {
	mock *MockCourierRep
}

// NewMockCourierRep creates a new mock instance.
func NewMockCourierRep(ctrl *gomock.Controller) *MockCourierRep {
	mock := &MockCourierRep{ctrl: ctrl}
	mock.recorder = &MockCourierRepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRep) EXPECT() *MockCourierRepMockRecorder {
	return m.recorder
}

// DeleteCourier mocks base method.
func (m *MockCourierRep) DeleteCourier(id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCourier", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCourier indicates an expected call of DeleteCourier.
func (mr *MockCourierRepMockRecorder) DeleteCourier(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCourier", reflect.TypeOf((*MockCourierRep)(nil).DeleteCourier), id)
}

// GetCourierFromDB mocks base method.
func (m *MockCourierRep) GetCourierFromDB(id uint16) (*model.SmallInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierFromDB", id)
	ret0, _ := ret[0].(*model.SmallInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierFromDB indicates an expected call of GetCourierFromDB.
func (mr *MockCourierRepMockRecorder) GetCourierFromDB(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierFromDB", reflect.TypeOf((*MockCourierRep)(nil).GetCourierFromDB), id)
}

// GetCouriersFromDB mocks base method.
func (m *MockCourierRep) GetCouriersFromDB() ([]model.SmallInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouriersFromDB")
	ret0, _ := ret[0].([]model.SmallInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCouriersFromDB indicates an expected call of GetCouriersFromDB.
func (mr *MockCourierRepMockRecorder) GetCouriersFromDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouriersFromDB", reflect.TypeOf((*MockCourierRep)(nil).GetCouriersFromDB))
}

// SaveCourierInDB mocks base method.
func (m *MockCourierRep) SaveCourierInDB(Courier *model.Courier) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCourierInDB", Courier)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCourierInDB indicates an expected call of SaveCourierInDB.
func (mr *MockCourierRepMockRecorder) SaveCourierInDB(Courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCourierInDB", reflect.TypeOf((*MockCourierRep)(nil).SaveCourierInDB), Courier)
}
