// Code generated by MockGen. DO NOT EDIT.
// Source: Service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	db "github.com/Baraulia/COURIER_SERVICE/db"
	gomock "github.com/golang/mock/gomock"
)

// MockCourierApp is a mock of CourierApp interface.
type MockCourierApp struct {
	ctrl     *gomock.Controller
	recorder *MockCourierAppMockRecorder
}

// MockCourierAppMockRecorder is the mock recorder for MockCourierApp.
type MockCourierAppMockRecorder struct {
	mock *MockCourierApp
}

// NewMockCourierApp creates a new mock instance.
func NewMockCourierApp(ctrl *gomock.Controller) *MockCourierApp {
	mock := &MockCourierApp{ctrl: ctrl}
	mock.recorder = &MockCourierAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierApp) EXPECT() *MockCourierAppMockRecorder {
	return m.recorder
}

// GetCouriers mocks base method.
func (m *MockCourierApp) GetCouriers() ([]db.SmallInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouriers")
	ret0, _ := ret[0].([]db.SmallInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCouriers indicates an expected call of GetCouriers.
func (mr *MockCourierAppMockRecorder) GetCouriers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouriers", reflect.TypeOf((*MockCourierApp)(nil).GetCouriers))
}

// GetOneCourier mocks base method.
func (m *MockCourierApp) GetOneCourier(id int) ([]db.SmallInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneCourier", id)
	ret0, _ := ret[0].([]db.SmallInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneCourier indicates an expected call of GetOneCourier.
func (mr *MockCourierAppMockRecorder) GetOneCourier(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneCourier", reflect.TypeOf((*MockCourierApp)(nil).GetOneCourier), id)
}
