// Code generated by MockGen. DO NOT EDIT.
// Source: Service.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "stlab.itechart-group.com/go/food_delivery/courier_service/dao"
)

// MockOrderApp is a mock of OrderApp interface.
type MockOrderApp struct {
	ctrl     *gomock.Controller
	recorder *MockOrderAppMockRecorder
}

// MockOrderAppMockRecorder is the mock recorder for MockOrderApp.
type MockOrderAppMockRecorder struct {
	mock *MockOrderApp
}

// NewMockOrderApp creates a new mock instance.
func NewMockOrderApp(ctrl *gomock.Controller) *MockOrderApp {
	mock := &MockOrderApp{ctrl: ctrl}
	mock.recorder = &MockOrderAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderApp) EXPECT() *MockOrderAppMockRecorder {
	return m.recorder
}

// AssigningOrderToCourier mocks base method.
func (m *MockOrderApp) AssigningOrderToCourier(order dao.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssigningOrderToCourier", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssigningOrderToCourier indicates an expected call of AssigningOrderToCourier.
func (mr *MockOrderAppMockRecorder) AssigningOrderToCourier(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssigningOrderToCourier", reflect.TypeOf((*MockOrderApp)(nil).AssigningOrderToCourier), order)
}

// GetAllServiceCompletedOrders mocks base method.
func (m *MockOrderApp) GetAllServiceCompletedOrders(limit, page, idService int) ([]dao.DetailedOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServiceCompletedOrders", limit, page, idService)
	ret0, _ := ret[0].([]dao.DetailedOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllServiceCompletedOrders indicates an expected call of GetAllServiceCompletedOrders.
func (mr *MockOrderAppMockRecorder) GetAllServiceCompletedOrders(limit, page, idService interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServiceCompletedOrders", reflect.TypeOf((*MockOrderApp)(nil).GetAllServiceCompletedOrders), limit, page, idService)
}

// GetDetailedOrdersById mocks base method.
func (m *MockOrderApp) GetDetailedOrdersById(Id int) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailedOrdersById", Id)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailedOrdersById indicates an expected call of GetDetailedOrdersById.
func (mr *MockOrderAppMockRecorder) GetDetailedOrdersById(Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailedOrdersById", reflect.TypeOf((*MockOrderApp)(nil).GetDetailedOrdersById), Id)
}
