// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package courierProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CourierServerClient is the client API for CourierServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourierServerClient interface {
	SendOrderToCourierService(ctx context.Context, in *OrderFields, opts ...grpc.CallOption) (*OrderStatusResponse, error)
}

type courierServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierServerClient(cc grpc.ClientConnInterface) CourierServerClient {
	return &courierServerClient{cc}
}

func (c *courierServerClient) SendOrderToCourierService(ctx context.Context, in *OrderFields, opts ...grpc.CallOption) (*OrderStatusResponse, error) {
	out := new(OrderStatusResponse)
	err := c.cc.Invoke(ctx, "/courier.CourierServer/SendOrderToCourierService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierServerServer is the server API for CourierServer service.
// All implementations must embed UnimplementedCourierServerServer
// for forward compatibility
type CourierServerServer interface {
	SendOrderToCourierService(context.Context, *OrderFields) (*OrderStatusResponse, error)
	mustEmbedUnimplementedCourierServerServer()
}

// UnimplementedCourierServerServer must be embedded to have forward compatible implementations.
type UnimplementedCourierServerServer struct {
}

func (UnimplementedCourierServerServer) SendOrderToCourierService(context.Context, *OrderFields) (*OrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOrderToCourierService not implemented")
}
func (UnimplementedCourierServerServer) mustEmbedUnimplementedCourierServerServer() {}

// UnsafeCourierServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourierServerServer will
// result in compilation errors.
type UnsafeCourierServerServer interface {
	mustEmbedUnimplementedCourierServerServer()
}

func RegisterCourierServerServer(s grpc.ServiceRegistrar, srv CourierServerServer) {
	s.RegisterService(&CourierServer_ServiceDesc, srv)
}

func _CourierServer_SendOrderToCourierService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFields)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServerServer).SendOrderToCourierService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/courier.CourierServer/SendOrderToCourierService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServerServer).SendOrderToCourierService(ctx, req.(*OrderFields))
	}
	return interceptor(ctx, in, info, handler)
}

// CourierServer_ServiceDesc is the grpc.ServiceDesc for CourierServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourierServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "courier.CourierServer",
	HandlerType: (*CourierServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOrderToCourierService",
			Handler:    _CourierServer_SendOrderToCourierService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "courierServer.proto",
}
