definitions:
  controller.listOrders:
    properties:
      data:
        items:
          $ref: '#/definitions/dao.DetailedOrder'
        type: array
    type: object
  controller.listShortOrders:
    properties:
      data:
        items:
          $ref: '#/definitions/dao.Order'
        type: array
    type: object
  dao.DetailedOrder:
    properties:
      courier_id:
        type: integer
      customer_address:
        type: string
      delivery_service_id:
        type: integer
      delivery_time:
        type: string
      id:
        type: integer
      name:
        type: string
      order_date:
        type: string
      phone_number:
        type: string
      picked:
        type: boolean
      restaurant_address:
        type: string
      status:
        type: string
    type: object
  dao.Order:
    properties:
      courier_id:
        type: integer
      customer_address:
        type: string
      delivery_service_id:
        type: integer
      delivery_time:
        type: string
      id:
        type: integer
      order_date:
        type: string
      picked:
        type: boolean
      restaurant_address:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: API Server
  title: COURIER_SERVICE
paths:
  /orders:
    get:
      description: get list of all orders by courier service id
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: iddeliveryservice
        in: query
        name: iddeliveryservice
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.listShortOrders'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetAllOrdersOfCourierService
      tags:
      - order
  /orders/bymonth:
    get:
      description: get list of completed orders by courier id sorted by month
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: idcourier
        in: query
        name: idcourier
        required: true
        type: integer
      - description: month
        in: query
        name: month
        required: true
        type: integer
      - description: year
        in: query
        name: year
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.listShortOrders'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetCourierCompletedOrdersByMonth
      tags:
      - order
  /orders/completed:
    get:
      description: get list of completed orders by courier id
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: idcourier
        in: query
        name: idcourier
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.listOrders'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetCourierCompletedOrders
      tags:
      - order
swagger: "2.0"
