definitions:
  dao.Order:
    properties:
      courier_id:
        type: integer
      customer_address:
        type: string
      delivery_service_id:
        type: integer
      delivery_time:
        type: string
      id:
        type: integer
      order_date:
        type: string
      picked:
        type: boolean
      restaurant_address:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: API Server for TodoList Application
  title: COURIER_SERVICE
paths:
  /orders/{id}:
    put:
      consumes:
      - application/json
      description: assign order to courier
      operationId: UpdateOrder
      parameters:
      - description: order_id
        in: path
        name: id
        required: true
        type: integer
      - description: id courier
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dao.Order'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      summary: UpdateOrder
      tags:
      - order
swagger: "2.0"
